### ISSUE TITLE
Nul--;

### ISSUE THREAD

**Issue by bitsycore** [Scorbutics/SmashAndDash#16]
Moins nul qu'avant mais juste décrémenté d'un

**Comment by bitsycore** [comment]
feature++;
line+=50000;
file+=50;
playable-=5000;

**Comment by bitsycore** [comment]
Any update on this issue ? It's already been more than 3 y

**Comment by Scorbutics** [comment]
I killed the original maintainer and took is place.
But I dunno how to code.

**Comment by bitsycore** [comment]
It polute my issue space
